/**
 * @file GeneratedSchemas.h
 * @brief Lookup functions for schemas generated from openapi.yaml.
 *
 * The implementations are generated by scripts/generate_schemas.py at
 * build time (requires -DAOSDL_GENERATE_SCHEMAS=ON). If schema generation
 * is disabled, these functions are not available.
 */
#pragma once

#include "utils/JsonSchema.h"

#include <string>

/// Look up a request body schema by OpenAPI operationId.
/// @throws std::runtime_error if the operation has no request schema.
const JsonSchema& aonx_request_schema(const std::string& operation_id);

/// Look up a named component schema (from components/schemas).
/// @throws std::runtime_error if the schema name is unknown.
const JsonSchema& aonx_component_schema(const std::string& name);
